### ISSUE TITLE
Expose Gorilla's router

### ISSUE THREAD

**Issue by adam-buckley** [taliesinmillhouse/little-server#1]
In Gorilla you can set up subrouters like (from their documentation):
```go
r := mux.NewRouter()
s := r.PathPrefix("/products").Subrouter()
// "/products/"
s.HandleFunc("/", ProductsHandler)
// "/products/{key}/"
s.HandleFunc("/{key}/", ProductHandler)
// "/products/{key}/details"
s.HandleFunc("/{key}/details", ProductDetailsHandler)
```
Currently this isn't doable with little-server since there's nowhere to set the router, not sure what the best route is to do this. Perhaps just exposing the router so mux based functions can be called directly on it? e.g.:
```go
// somewhere in my main.go
s := server.Router.PathPrefix("/products").Subrouter()
// everything I do to "s" will be mapped to little-servers mux router
```
Either that or Get/SetRouter functions but is slightly more confusing to use and maintain.

**Comment by taliesinmillhouse** [comment]
I've updated the Router so it can be accessed outside of the package. See [333e268](https://github.com/taliesinmillhouse/little-server/commit/333e268f9c16f9edef1e4d50ac0143dfd10b22d1).
